//action types
const GET_PRODUCTS = "GET_PRODUCTS";
const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
const ADD_PRODUCT = "ADD_PRODUCT";
const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";

const INC = "INC";
const DEC = "DEC";
