export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";

export const TITLE_CHANGE = "TITLE_CHANGE";
export const PRICE_CHANGE = "PRICE_CHANGE";
export const CATEGORY_CHANGE = "CATEGORY_CHANGE";
